### ISSUE TITLE
Binaries for 0.95?

### ISSUE THREAD

**Issue by rr-** [idapython/bin#1]
Seeing how there is a number of fixes available for 0.95:

https://github.com/idapython/src/commits/master

could we get binaries compatible with IDA 6.95 demo? Thanks

**Comment by aundro** [comment]
I have decided against continuing to publish binaries here: 
- updating them all every time is just a waste of time,
- they can be re-built provided you have the right tools (SWiG 2.0.12 being the most demanding)

If you don't have those tools but an active support plan, you can contact us at: support -at- hex-rays.com and we'll gladly send you new binaries.

**Comment by rr-** [comment]
Thank you for prompt reply. I think it's worth mentioning on IDA's page that the demo version doesn't feature IDAPython, because without the binaries nor SDK, trial users are no longer able to install it by hand.

**Comment by aundro** [comment]
You're right about the demo version. We'll update that asap! 
Thanks for the feedback!
