### ISSUE TITLE
How to install "pip install package"

### ISSUE THREAD

**Issue by michaelii** [idapython/bin#2]
Hi

I want to use IDApython and use default Python2.7 by IDApro 6.95

Every thing is good, but "pip install"

Can you tell me how to install the package on the IDApython?

Thanks

Michael

**Comment by lallousx86** [comment]
There is no PIP package for IDAPython.

IDAPython usually comes with IDA's installer. Otherwise, you have to grab the sources from this repo and build it yourself.
