### ISSUE TITLE
is idapython on IDA6.3  for linux  accessable?

### ISSUE THREAD

**Issue by lzyplayer** [idapython/bin#3]

**Comment by lzyplayer** [comment]
https://www.hex-rays.com/products/ida/support/ida/linux_pyside_python27_package.tgz
but password is needed,
address:
https://www.hex-rays.com/products/ida/support/download.shtml
Thanks for the reply.

**Comment by lallousx86** [comment]
Hello Izyplayer, 

All in all, older versions are not supported. If you have the right IDA SDK, download the sources and compile them yourself.

You can see here as well: https://code.google.com/archive/p/idapython/
https://code.google.com/archive/p/idapython/downloads?page=1

etc...
