### ISSUE TITLE
is it possible to install idapython on ida free?

### ISSUE THREAD

**Issue by andreafioraldi** [idapython/bin#5]
I have installed the new ida free 7.0 and I'm asking if i can install idapython on it. Thanks :)

**Comment by tosanjay** [comment]
I also tried this, but failed. Looks like , IDA free does not load IDAPython plugins. So, the question is:
Is there any way around this?

**Comment by lallousx86** [comment]
No, not officially. It seems a limitation of the free IDA version. Forcefully making the plugin work could be in violation of this free version terms.

**Comment by aundro** [comment]
There's a boatload of C functions that IDA free doesn't export. If you somehow manage to get IDAPython to compile against the free IDA libraries, by then you'll have had to strip it of so much of its functionality that it's gonna be entirely useless.
