### ISSUE TITLE
CallStackWalk failed to reconstruct the call stack

### ISSUE THREAD

**Issue by confile** [idapython/bin#6]
I tried debugging in Win XP and Wind 7 and still had the same problems with the call stack. I attached the example I used from lena 26 tutorial.
Here is what I did. Start the app in the debugger. Press the Register button. When the following Error message appear, hit pause in the debugger:

<img width="690" alt="markiert__9_e-mails_" src="https://user-images.githubusercontent.com/64265/47252786-71665380-d44a-11e8-97f2-cf3be2b25f99.png">

In Ollydbg you get the following stack trace:

PastedGraphic-2.png
![image](https://user-images.githubusercontent.com/64265/47252789-7b885200-d44a-11e8-8556-ccf206a7f14f.png)

Doing the same in IDA leads to the following stack trace:

PastedGraphic-3.png
![image](https://user-images.githubusercontent.com/64265/47252791-8216c980-d44a-11e8-9381-18c9a0d5ec9e.png)

**Comment by drmichaelgorski** [comment]
[OutlookExpressBackup.exe.zip](https://github.com/idapython/bin/files/2497908/OutlookExpressBackup.exe.zip)

Here is the example I used.

**Comment by lallousx86** [comment]
This is not IDAPython related. Closing.
